replicaCount: 2

image:
  repository: k8s-frontend
  tag: "1.0"
  pullPolicy: Never

service:
  type: NodePort
  port: 80
  nodePort: 30080

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60