apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
    chart: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: backend
    release: {{ .Release.Name }}